In [98]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

pd.pandas.set_option('display.max_columns',None)

In [99]:
# Read feature engineering train data 
dataset = pd.read_csv('X_train.csv')

In [100]:
dataset

Id  SalePrice  MSSubClass  MSZoning  LotFrontage   LotArea  Street  \
0        1   2.505338    0.235294      0.75     0.496892  0.431124     1.0   
1        2   2.493950    0.000000      0.75     0.573315  0.457169     1.0   
2        3   2.510994    0.235294      0.75     0.513817  0.489044     1.0   
3        4   2.472277    0.294118      0.75     0.466412  0.456111     1.0   
4        5   2.520050    0.235294      0.75     0.590747  0.535696     1.0   
...    ...        ...         ...       ...          ...       ...     ...   
1455  1456   2.490934    0.235294      0.75     0.478970  0.417682     1.0   
1456  1457   2.505923    0.000000      0.75     0.594947  0.520254     1.0   
1457  1458   2.525179    0.294118      0.75     0.502640  0.444991     1.0   
1458  1459   2.473548    0.000000      0.75     0.513817  0.459623     1.0   
1459  1460   2.476671    0.000000      0.75     0.549956  0.464150     1.0   

      Alley  LotShape  LandContour  Utilities  LotConfig  LandSlope  \
0       1.0  0.000000     0.333333        1.0       0.00        0.0   
1       1.0  0.000000     0.333333        1.0       0.50        0.0   
2       1.0  0.333333     0.333333        1.0       0.00        0.0   
3       1.0  0.333333     0.333333        1.0       0.25        0.0   
4       1.0  0.333333     0.333333        1.0       0.50        0.0   
...     ...       ...          ...        ...        ...        ...   
1455    1.0  0.000000     0.333333        1.0       0.00        0.0   
1456    1.0  0.000000     0.333333        1.0       0.00        0.0   
1457    1.0  0.000000     0.333333        1.0       0.00        0.0   
1458    1.0  0.000000     0.333333        1.0       0.00        0.0   
1459    1.0  0.000000     0.333333        1.0       0.00        0.0   

      Neighborhood  Condition1  Condition2  BldgType  HouseStyle  OverallQual  \
0         0.636364         0.4         1.0      0.75         1.0     0.666667   
1         0.500000         0.2         1.0      0.75         0.6     0.555556   
2         0.636364         0.4         1.0      0.75         1.0     0.666667   
3         0.727273         0.4         1.0      0.75         1.0     0.666667   
4         1.000000         0.4         1.0      0.75         1.0     0.777778   
...            ...         ...         ...       ...         ...          ...   
1455      0.590909         0.4         1.0      0.75         1.0     0.555556   
1456      0.545455         0.4         1.0      0.75         0.6     0.555556   
1457      0.727273         0.4         1.0      0.75         1.0     0.666667   
1458      0.363636         0.4         1.0      0.75         0.6     0.444444   
1459      0.227273         0.4         1.0      0.75         0.6     0.444444   

      OverallCond  YearBuilt  YearRemodAdd  RoofStyle  RoofMatl  Exterior1st  \
0           0.500   0.036765      0.098361        0.0       0.0          1.0   
1           0.875   0.227941      0.524590        0.0       0.0          0.4   
2           0.500   0.051471      0.114754        0.0       0.0          1.0   
3           0.500   0.669118      0.606557        0.0       0.0          0.2   
4           0.500   0.058824      0.147541        0.0       0.0          1.0   
...           ...        ...           ...        ...       ...          ...   
1455        0.500   0.058824      0.131148        0.0       0.0          1.0   
1456        0.625   0.235294      0.377049        0.0       0.0          0.7   
1457        1.000   0.507353      0.081967        0.0       0.0          0.9   
1458        0.625   0.441176      0.245902        1.0       0.0          0.4   
1459        0.625   0.316176      0.721311        0.0       0.0          0.6   

      Exterior2nd  MasVnrType  MasVnrArea  ExterQual  ExterCond  Foundation  \
0             1.0        0.50    0.122500   0.666667   1.000000        1.00   
1             0.3        0.25    0.000000   0.333333   1.000000        0.50   
2             1.0        0.50    0.101250   0.6

In [101]:
# splitting data into dependent and independent feature 
y_train = dataset[['SalePrice']]
X_train = dataset.drop(['Id','SalePrice'],axis=1)

In [102]:
from sklearn.linear_model import LinearRegression


selecter = SelectFromModel(Lasso(alpha=0.001))
selecter.fit(X_train,y_train)


SelectFromModel(estimator=Lasso(alpha=0.001))

In [103]:
selecter.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [104]:
selecter.estimator_.coef_

array([-0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.03349273,  0.        ,  0.        ,  0.        ,
        0.        ,  0.02924228,  0.        , -0.        , -0.0101945 ,
        0.00023413,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.00247492,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.00035451,  0.        ,  0.        ,  0.        ,  0.        ,
        0.02243636,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.00881204,  0.        ,  0.        ,
        0.        ,  0.01342366,  0.00494298, -0.        ,  0.00779989,
        0.01113374,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.        ,  0.        ,  0.  

In [107]:
selected_feat = X_train.columns[(selecter.get_support())]
X= X_train[selected_feat]
X

Neighborhood  OverallQual  YearRemodAdd  RoofStyle  BsmtExposure  \
0         0.636364     0.666667      0.098361        0.0          0.25   
1         0.500000     0.555556      0.524590        0.0          1.00   
2         0.636364     0.666667      0.114754        0.0          0.50   
3         0.727273     0.666667      0.606557        0.0          0.25   
4         1.000000     0.777778      0.147541        0.0          0.75   
...            ...          ...           ...        ...           ...   
1455      0.590909     0.555556      0.131148        0.0          0.25   
1456      0.545455     0.555556      0.377049        0.0          0.25   
1457      0.727273     0.666667      0.081967        0.0          0.25   
1458      0.363636     0.444444      0.245902        1.0          0.50   
1459      0.227273     0.444444      0.721311        0.0          0.25   

      CentralAir  GrLivArea  KitchenQual  FireplaceQu  GarageType  \
0            1.0   0.624795     0.666667          0.2         0.8   
1            1.0   0.519684     0.333333          0.6         0.8   
2            1.0   0.639489     0.666667          0.6         0.8   
3            1.0   0.626179     0.666667          0.8         0.4   
4            1.0   0.708471     0.666667          0.6         0.8   
...          ...        ...          ...          ...         ...   
1455         1.0   0.612042     0.333333          0.6         0.8   
1456         1.0   0.689203     0.333333          0.6         0.8   
1457         1.0   0.728911     0.666667          0.8         0.8   
1458         1.0   0.463383     0.666667          0.2         0.8   
1459         1.0   0.518000     0.333333          0.2         0.8   

      GarageFinish  GarageCars  
0         0.666667        0.50  
1         0.666667        0.50  
2         0.666667        0.50  
3         0.333333        0.75  
4         0.666667        0.75  
...            ...         ...  
1455      0.666667        0.50  
1456      0.333333        0.50  
1457      0.666667        0.25  
1458      0.333333        0.25  
1459      1.000000        0.25  

[1460 rows x 12 columns]

In [108]:

y = y_train
y

SalePrice
0      2.505338
1      2.493950
2      2.510994
3      2.472277
4      2.520050
...         ...
1455   2.490934
1456   2.505923
1457   2.525179
1458   2.473548
1459   2.476671

[1460 rows x 1 columns]

In [109]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [110]:
from sklearn.metrics import mean_squared_error,r2_score
model = LinearRegression()
model = model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print('Mean Squared error: ',mean_squared_error(y_test,y_pred))
print('R2 Score: ', r2_score(y_test,y_pred)) 

Mean Squared error:  0.00016160909937798395
R2 Score:  0.8434336003578965


In [111]:
y_pred

array([[2.51316086],
       [2.47307717],
       [2.45723406],
       [2.51321705],
       [2.45382693],
       [2.44322459],
       [2.52080763],
       [2.46488125],
       [2.5778527 ],
       [2.48968038],
       [2.50434281],
       [2.48033488],
       [2.50935352],
       [2.45686168],
       [2.46241273],
       [2.46377113],
       [2.51713919],
       [2.44952035],
       [2.46779654],
       [2.49596215],
       [2.46624019],
       [2.48771838],
       [2.43329415],
       [2.49090122],
       [2.50253205],
       [2.49830195],
       [2.49594333],
       [2.42122443],
       [2.52000317],
       [2.45728986],
       [2.47979358],
       [2.50028553],
       [2.47320308],
       [2.53806602],
       [2.53783022],
       [2.50308188],
       [2.53100866],
       [2.46011649],
       [2.52006806],
       [2.53823869],
       [2.50430975],
       [2.46901532],
       [2.50523757],
       [2.53064539],
       [2.54311252],
       [2.47074175],
       [2.44938659],
       [2.464